# Correct pubspec.yaml structure:

name: korgan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4  # Network detection
  logger: ^2.6.0
  dio: ^5.8.0+1
  http: ^1.4.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_html: ^3.0.0
  flutter_html_all: ^3.0.0
  url_launcher: ^6.3.2
  flutter_inappwebview: ^6.1.5
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  intl: ^0.20.2
  pointer_interceptor: ^0.10.1
  path_provider: ^2.1.5
  crypto: ^3.0.6
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  share_plus: ^11.0.0
  device_info_plus: ^11.5.0
  mime: ^2.0.0
  cross_file: ^0.3.4+2
  flutter_pdfview: ^1.4.1
  pdfx: ^2.9.2
  photo_view: ^0.15.0
  video_player: ^2.10.0
  audioplayers: ^6.5.0
  path: ^1.9.1
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  go_router: ^16.0.0
  universal_html: ^2.2.4
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5


flutter:
  uses-material-design: true
  
